### ISSUE TITLE
Slow now 1.2 version for split

### ISSUE THREAD

**Issue by snavsvpn** [AbdurazaaqMohammed/AntiSplit-M#1]
With version 1.2 the Split to .apk process is now slow; Also when I want to split .xapk the app crashes.

**Comment by AbdurazaaqMohammed** [comment]
> With version 1.2 the Split to .apk process is now slow

It may seem this way, because it only starts antisplit when you selected the place to save, but it will be more efficient, before it was writing it to the cache directory and then copying it. Now I added an option to save directly to the same directory as the selected file, like AntiSplit-G2 does, so there can be the best of both worlds.

> Also when I want to split .xapk the app crashes.

It should be fixed now in the latest release

**Comment by AbdurazaaqMohammed** [comment]
@snavsvpn Sorry for such late response 
No don't select the directory, just disable this option then it will automatically save there and it should be faster now
![WhatsApp Image 2024-06-29 at 12 48 52_0c45fbf3](https://github.com/AbdurazaaqMohammed/AntiSplit-M/assets/56937889/8d757ff6-80f2-4174-ace3-9a12d6ee52df)
