### ISSUE TITLE
Question about signing the APK

### ISSUE THREAD

**Issue by 54m4d** [AbdurazaaqMohammed/AntiSplit-M#117]
Hello Abdurazaaq 

Since Revanced Manager signs the APK before installation, should the `Sign the APK after merging` option in AntiSplit be turned on or off?

And what could happen if the APK is signed by both AntiSplit and Revanced Manager?

I would like to understand the pros and cons of this option, as well as any potential risks or issues that could arise.

Thanks!

**Comment by AbdurazaaqMohammed** [comment]
It will work whether it is on or off. If you turn it off AntiSplit M will finish saving a little faster.

> And what could happen if the APK is signed by both AntiSplit and Revanced Manager?

There should be no difference whether AntiSplit M signed it or not. Whenever an APK is modified, the signature will become invalid and it must be signed in order to install it (if ReVanced Manager did not sign it, the signature would not be valid and it would not install even if AntiSplit M signed it before).
