### ISSUE TITLE
Installed app crashes & doesn't open

### ISSUE THREAD

**Issue by Th3-A6add0n** [AbdurazaaqMohammed/AntiSplit-M#49]
I tried merging Lightroom (9.5.0) and everything went well with the merging & signing. The app even gets installed but as soon as I open the app, a black screen pops up for split second & then nothing.
I've tried multiple methods, the default merging behaviour, selecting all the right things according to my device, letting antisplit M itself automatically select things for my device.

PS: the said app gets installed successfully if I use SAI & it even works fine. I'm using Antisplit M just so I can use the ReVanced patches

PPS: Yes, I tried the app even before patching with ReVanced.

**Comment by AbdurazaaqMohammed** [comment]
The problem is that Adobe added Pairip/Google加固 Integrity to Lightroom since v9.4.2, which checks signature verification among other things to check if the APK was modified. There are ways to bypass it, but it's not the job of AntiSplit app. If you want a version newer than 9.4.1 you should look for alternative patched sources.

**Comment by Th3-A6add0n** [comment]
> The problem is that Adobe added Pairip/Google加固 Integrity to Lightroom since v9.4.2, which checks signature verification among other things to check if the APK was modified. There are ways to bypass it, but it's not the job of AntiSplit app. If you want a version newer than 9.4.1 you should look for alternative patched sources.

Hypocrite Google, taking privacy & security seriously when it benefits them 🥲
