### ISSUE TITLE
You don't need to support Android 1.6

### ISSUE THREAD

**Issue by kitadai31** [AbdurazaaqMohammed/AntiSplit-M#59]
You don't need to set minSdk to 4.
Because split APK is supported from Android 5.0.
This means that any app that supports Android 4.4 or lower are absolutely provided with a single APK as well.

I'm sorry if you know this, but I just wanted to let you know.
I believe that setting minSdk to 21 makes your development easier.

**Comment by AbdurazaaqMohammed** [comment]
I know it doesn't make a lot of sense, but there are a few cases for it

- You can still do modding on old Android versions, even if device can't run it 
  - For some apps supported below 5.0, there is non split for each architecture, but universal APK only as bundle ([example](https://www.apkmirror.com/apk/fundevs/mp3-video-converter/mp3-video-converter-2-6-10-release)), to support all devices when modding easier to download split APK and merge
- In fact, since splits not supported below Android 5, if someone shared APK with compatible minSdkVersion but split to someone with device below Android 5, the only way to install it will be to merge
- And in my case, I test and use this app on Android 2.3.3 (SDK 10) emulator (oldest version I could get working), to reduce load on my PC

I know these are relatively rare use cases, I won't hesitate to increase the minSdkVersion if it is necessary, but I won't make it incompatible with these cases if not
