### ISSUE TITLE
XAPK Error

### ISSUE THREAD

**Issue by MAXBURAOT** [AbdurazaaqMohammed/AntiSplit-M#61]
Using WindyApp.xapk
![Screenshot_2024-09-04-07-46-42-56_8535ff50172f7e38e5d0e213e508cb1d](https://github.com/user-attachments/assets/b4c48e4c-9c85-4f3d-a72a-8bb95a15cd91)

java.lang.RuntimeException: com.abdurazaaqmohammed.AntiSplit.main.MismatchedSplitsException: Error: Key (the app will not run without it) split (config.x86.apk) has a mismatched version code.
com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:394)
com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:264)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)

Output directory: /storage/emulated/0/Download/aaa/pair/Windy.app_50.1.0_apkcombo.com_antisplit.apk
Searching apk files…
/document/primary:Download/aaa/pair/Windy.app_50.1.0_apkcombo.com.xapk
Extracted co.windyapp.android.apk
Extracted config.x86.apk
Extracted config.ja.apk
Extracted config.xxhdpi.apk
Extracted config.it.apk
Extracted config.x86_64.apk
Extracted config.th.apk
Extracted config.nl.apk
Extracted config.mdpi.apk
Extracted config.de.apk
Extracted config.hdpi.apk
Extracted config.en.apk
Extracted config.zh.apk
Extracted config.ldpi.apk
Extracted config.ru.apk
Extracted config.tvdpi.apk
Extracted config.pt.apk
Extracted config.pl.apk
Extracted config.es.apk
Extracted config.ms.apk
Extracted config.fi.apk
Extracted config.ar.apk
Extracted config.hi.apk
Extracted config.xxxhdpi.apk
Extracted config.vi.apk
Extracted config.in.apk
Extracted config.fr.apk
Extracted config.arm64_v8a.apk
Extracted config.xhdpi.apk
Extracted config.armeabi_v7a.apk
Skipping manifest.json: Not an APK file
Skipping APKComboInstaller.url: Not an APK file
Skipping icon.png: Not an APK file
Found apk files: 30

**Comment by AbdurazaaqMohammed** [comment]
As it says, x86 and some other splits have mismatched version code, I notice this happens with some apps on APKCombo where some of the splits are outdated sometimes. I don't know how they make this error, it is a big problem because the splits won't install (Even in APKCombo installer) and if you force merge it, it installs but any split with mismatched version code won't work.

 I recommend downloading from APKMirror when available or APKPure instead of APKCombo, this app is available on APKMirror - https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/windy-wind-weather-forecast-50-1-0-release

By the way, I know the app can run without x86 (or whatever split is mismatched) library on any devices that don't require that split, but I show the error for all architectures because if merging universal APK all architecture should be working. (If you enable "Select splits for your device specifications", it should not have the error, atleast not for x86)
