### ISSUE TITLE
Error page buttons improvements

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#68]
I think the buttons of the error page need some improvements or adjustments, as at first glance it looks like there is no 3rd button (`Copy log`) as it is really hidden.
Also, I think the buttons won't even need a scroll bar with some tweaking.

https://github.com/user-attachments/assets/7da27d1b-a6ca-4088-b82d-46fed0a4bce1

**Comment by AbdurazaaqMohammed** [comment]
This is default behavior of the material alert dialog (Infact the regular one was worse because the buttons were not scrollable and the last buttons were not visible at all), I don't know how to improve it

**Comment by drogga** [comment]
OP - I wouldn't close this on your place, as it's still a thing, in future the dev. might find a way to fix this, either by making/fitting them horizontally or making them as buttons with icons, instead of textual and a hint on long press of what they do if it's not clear enough and then close the ticket.

**Comment by AbdurazaaqMohammed** [comment]
![WhatsApp Image 2024-09-12 at 12 20 25_c5192289](https://github.com/user-attachments/assets/1a2ae1a0-51a5-4d17-8365-cd2ec3c21df9)
