### ISSUE TITLE
Windy.App crashes after merging

### ISSUE THREAD

**Issue by TheRedNet** [AbdurazaaqMohammed/AntiSplit-M#72]
I tried everything to get a functioning non crashing merged apk of Windy.App
First i merged the latest apkm from Apkmirror. Windy installed from this apk crashes immediatly after launching
I tried it again with the Autamatically select splits for your device enabled. Again Windy crashes.
I install windy from Play Store it lauches. I then use the Select from installed apps to make a Windy apk. uninstalled original windy and install from merged apk. Windy crashes again.
i download an older version of windy from apkmirror(55.0.0) try again both with all splits and only device splits. both crash.
Phone: Samsung galaxy A13 Android 14 Antisplit-M version: tried both 2.0 and 1.6.6.2

**Comment by AbdurazaaqMohammed** [comment]
The problem is that this app added Pairip/Google加固 Integrity protection a long time ago (You can tell by how long the app has only had bundles available to download on APKMirror, for some reason apps with pairip have been bundle only for a long time, before Google stopped providing non split APKs for other apps like Twitter/X), which checks signature verification among other things to check if the APK was modified. There are ways to bypass it, but it's not the job of AntiSplit app.

If you are trying to patch this app with ReVanced it won't work, you should try the last version that is not split or look for alternative pre patched sources.
