### ISSUE TITLE
Error logs not scrollable

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#75]
https://github.com/user-attachments/assets/b15dbc40-c3a6-46a6-93c8-16cffb5800df

**Comment by drogga** [comment]
I prefer it without WordWrap (can be optional, even tho I think it's unnecessary, for me personally it's harder to read with word wrap) and ofc. with a horizontal scrollbar, maybe even call the dialog title Error or Log, instead of a cropped part of the first line of the log (unless you think it's better that way).

**Comment by AbdurazaaqMohammed** [comment]
Fixed
