### ISSUE TITLE
Currently selected theme bugs

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#84]
1. In light theme, it is not visible that the currently selected theme is the light theme.
![Screenshot_20240914_033351_AntiSplit M](https://github.com/user-attachments/assets/72f0096a-5417-416a-8912-9882adf09915)
-
2. System theme button is not shown as currently selected theme when selected.

https://github.com/user-attachments/assets/6411a103-8a9e-4a20-b116-c6d8819ad653

**Comment by 0xrxL** [comment]
Oh...you compiled the app from the latest commit.

Anyway the current selected theme could be rounded instead squared. @AbdurazaaqMohammed

**Comment by AbdurazaaqMohammed** [comment]
> System theme button is not shown as currently selected theme when selected.

Fixed, I update the last release instead because the changes are minor

> In light theme, it is not visible that the currently selected theme is the light theme.
> the current selected theme could be rounded instead squared

Well, this is how the MaterialButtonToggleGroup looks, I don't know why the selection in light mode is barely visible, at least it looks a little better for me

![image](https://github.com/user-attachments/assets/a7bb13ae-5bee-44be-94b0-cf9d59708e60)
