### ISSUE TITLE
done

### ISSUE THREAD

**Issue by supergame9x** [AbdurazaaqMohammed/AntiSplit-M#94]
done

**Comment by AbdurazaaqMohammed** [comment]
Sorry for responding late, I replicate this issue, but only on Roblox, not on other apps with pairip. It just gets stuck after a while, there is no error. It's not xapk compression problem, same happens with apkm or extracted files. Not size issue either I tried with 700MB file. Strangely if you enable sign it works, the only difference there is that the merged APK saved to the cache dir before signing and copying, so for some reason it not saving properly to the output file directly. I still trying to think of a good way to fix this, it is hard to detect because there is no error, and it should not save to the cache dir and copy it for apps that don't need to

**Comment by supergame9x** [comment]
If convert ok, apk crash when open bro. Is there a faster way to contact like email or Telegram? I want to talk to you

**Comment by AbdurazaaqMohammed** [comment]
My telegram is same as github username

**Comment by AbdurazaaqMohammed** [comment]
It should save properly in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
